
scraper:
  # Wikipedia
  host: https://en.wikipedia.org/wiki/Main_Page
  crawl_host: https://en.wikipedia.org
  log_dir: logs
  save_dir: scraped_data
  img_dir: images
  log_file: debug.log
  browser_headers: {"User-Agent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/33.0"}
  # Width Approx Add ( MAX SIZE IMAGE AVAIL WILL BE RETURNED BY WIKI API )
  img_size_approx: 1920

